#!/bin/bash
# Code Agent v2.0 - 代码运行与调试
# 小虾 🦐 | 2026-03-06

set -e

WORKSPACE="/home/openclaw/.openclaw/workspace/obsidian-repo"
LOG_BASE="$WORKSPACE/logs/code-agent"
mkdir -p "$LOG_BASE"

log() {
    echo "[$(date '+%H:%M:%S')] $1"
}

# ============================================================
# 环境检测
# ============================================================

check_env() {
    log "🔍 检测 Python 环境..."
    
    echo ""
    echo "=== Python 版本 ==="
    python3 --version 2>&1 || { log "❌ Python3 未安装"; return 1; }
    
    echo ""
    echo "=== 已安装模块 ==="
    python3 << 'EOF'
import sys
modules = ['torch', 'numpy', 'gymnasium', 'matplotlib']
for mod in modules:
    try:
        m = __import__(mod)
        ver = getattr(m, '__version__', 'unknown')
        print(f'✅ {mod}: {ver}')
    except ImportError:
        print(f'❌ {mod}: 未安装')
EOF
    
    echo ""
    echo "=== 系统信息 ==="
    uname -a
    
    echo ""
    log "✅ 环境检测完成"
}

# ============================================================
# 运行代码
# ============================================================

run_code() {
    local script="$1"
    local log_dir="$LOG_BASE/$(date +%Y%m%d_%H%M%S)_$(basename "$script" .py)"
    
    if [ ! -f "$script" ]; then
        log "❌ 文件不存在：$script"
        return 1
    fi
    
    log "🚀 运行：$script"
    log "📁 日志：$log_dir"
    mkdir -p "$log_dir"
    
    # 运行并捕获输出
    python3 "$script" > "$log_dir/stdout.log" 2> "$log_dir/stderr.log"
    EXIT_CODE=$?
    
    # 分析结果
    echo ""
    if [ $EXIT_CODE -eq 0 ]; then
        log "✅ 运行成功!"
        echo ""
        echo "=== 输出摘要 ==="
        tail -20 "$log_dir/stdout.log"
    else
        log "❌ 运行失败 (退出码：$EXIT_CODE)"
        echo ""
        echo "=== 错误信息 ==="
        cat "$log_dir/stderr.log"
    fi
    
    echo ""
    echo "=== 完整日志 ==="
    echo "stdout: $log_dir/stdout.log"
    echo "stderr: $log_dir/stderr.log"
    
    # 返回日志目录
    echo "$log_dir"
}

# ============================================================
# 自动调试
# ============================================================

debug_error() {
    local stderr_file="$1"
    
    if [ ! -f "$stderr_file" ]; then
        log "❌ 错误文件不存在：$stderr_file"
        return 1
    fi
    
    log "🔧 分析错误..."
    echo ""
    
    python3 << EOF
import re

ERROR_PATTERNS = {
    'ModuleNotFoundError': r"ModuleNotFoundError: No module named '([^']+)'",
    'NameError': r"NameError: name '([^']+)' is not defined",
    'AttributeError': r"AttributeError: '([^']+)' object has no attribute '([^']+)'",
    'IndexError': r"IndexError: (.+)",
    'KeyError': r"KeyError: '([^']+)'",
    'ValueError': r"ValueError: (.+)",
    'RuntimeError': r"RuntimeError: (.+)",
}

FIX_SUGGESTIONS = {
    'ModuleNotFoundError': '''
修复建议:
1. 安装缺失模块：pip install <module_name>
2. 检查虚拟环境是否激活
3. 确认 requirements.txt 已安装
''',
    'NameError': '''
修复建议:
1. 检查变量拼写是否正确
2. 确保变量在使用前已定义
3. 检查缩进和 scope
''',
    'AttributeError': '''
修复建议:
1. 检查对象类型是否正确
2. 确认属性/方法存在
3. 查看文档确认 API
''',
    'IndexError': '''
修复建议:
1. 检查数组/列表长度
2. 调整索引范围
3. 添加边界检查
''',
    'KeyError': '''
修复建议:
1. 检查字典键是否存在
2. 使用 .get() 方法提供默认值
3. 添加键存在性检查
''',
    'ValueError': '''
修复建议:
1. 检查输入数据格式
2. 确认数据类型正确
3. 查看函数文档
''',
    'RuntimeError': '''
修复建议:
1. 查看完整堆栈跟踪
2. 检查输入数据和前置条件
3. 可能需要重构代码
'''
}

with open('$stderr_file', 'r') as f:
    error_text = f.read()

for error_type, pattern in ERROR_PATTERNS.items():
    match = re.search(pattern, error_text)
    if match:
        print(f"错误类型：{error_type}")
        print(f"错误详情：{match.group(0)}")
        print(FIX_SUGGESTIONS.get(error_type, '请人工检查代码'))
        break
else:
    print("错误类型：Unknown")
    print("请查看完整错误日志")
EOF
    
    echo ""
    log "✅ 调试分析完成"
}

# ============================================================
# 生成依赖安装脚本
# ============================================================

generate_requirements() {
    local script="$1"
    local output="${2:-requirements.txt}"
    
    log "📝 分析依赖：$script"
    
    python3 << EOF
import re
from pathlib import Path

# 常见模块映射
MODULE_TO_PACKAGE = {
    'torch': 'torch',
    'numpy': 'numpy',
    'gymnasium': 'gymnasium',
    'cv2': 'opencv-python',
    'PIL': 'pillow',
    'matplotlib': 'matplotlib',
    'pandas': 'pandas',
    'sklearn': 'scikit-learn',
}

script = Path('$script').read_text()

# 提取 import 语句
imports = set()
for line in script.split('\n'):
    line = line.strip()
    if line.startswith('import '):
        module = line.split()[1].split('.')[0]
        imports.add(module)
    elif line.startswith('from '):
        module = line.split()[1].split('.')[0]
        imports.add(module)

# 生成 requirements.txt
print("# Auto-generated requirements")
print("# Generated by Code Agent v2.0")
print()
for module in sorted(imports):
    package = MODULE_TO_PACKAGE.get(module, module)
    print(package)

print()
print("# Install with: pip install -r requirements.txt")
EOF
    
    log "✅ 依赖分析完成 → $output"
}

# ============================================================
# 主函数
# ============================================================

case "${1:-help}" in
    check|env)
        check_env
        ;;
    run)
        run_code "${2:-}"
        ;;
    debug)
        debug_error "${2:-}"
        ;;
    requirements|deps)
        generate_requirements "${2:-}"
        ;;
    help|*)
        echo "Code Agent v2.0 - 代码运行与调试"
        echo ""
        echo "用法：$0 <command> [args]"
        echo ""
        echo "命令:"
        echo "  check|env              检测 Python 环境"
        echo "  run <script.py>        运行 Python 代码"
        echo "  debug <stderr.log>     分析错误日志"
        echo "  requirements <script>  生成依赖列表"
        echo "  help                   显示帮助"
        echo ""
        echo "示例:"
        echo "  $0 check"
        echo "  $0 run code/rl-distillation/cartpole-distill.py"
        echo "  $0 debug logs/20260306_001500/stderr.log"
        echo "  $0 requirements code/rl-distillation/cartpole-distill.py"
        ;;
esac
